### ISSUE TITLE
Setup Kanban Board

### ISSUE THREAD

**Issue by williamrolando88** [williamrolando88/My-catalog#5]
Hi,

We are a team of 2 people, and you can look at or Kanban Project [here](https://github.com/williamrolando88/My-catalog/projects/1)

For the division of task:
- Team member 1: @yigitm 
- Team member 2: @williamrolando88

**Comment by AshakaE** [comment]
Hi @williamrolando88  , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights

- [x] Link to Kanban board ✔️ 
- [x] List of team member(s) ✔️   

## Required Changes ♻️
_Check the comments under the review._

- [ ] Team member @williamrolando88 has more points compared to @yigitm, please share the workload evenly  or with a difference of less than 5 points

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by williamrolando88** [comment]
Hi, we already sorted the difference in workload, the differences are in the group task itself, I assigned myself just as the requirements say:

>Each of the team members should assign themselves to the cards as divided in the [project requirements divided by team member](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things_divided.md) (and time estimate distributions should be fair - no single person should be doing all of the most time-consuming tasks). Decide who will be the assignee for the cards marked as group tasks. All cards on your Kanban board should have assignees.

We shared this group task together and for the other assignments, we have 9 points for each
